### ISSUE TITLE
NPE at LastCommitView:39 (onItemClick)

### ISSUE THREAD

**Issue by ghost** [rtyley/agit#30]
i clone a repository and it fails or if it takes a longer time due to size etc. 

when i click on "Latest Commit" before the repository is fully initialized, it throws a NullpointerException.

Package Version 1.22 (110800811)

**Comment by rtyley** [comment]
Thanks @williausrohr - I'll take a look. Ideally the repo should never be able get in an inconsistent state like this (ie have a ref pointing to a commit that's not actually available, which seems to be what's going wrong here). 
The user-experience of a faulty repo can probably be made a bit more pleasant with some defensive coding, but if the faulty repo isn't too large (less than 10MB) feel free to copy it off your sdcard (/sdcard/git-repos) and to send it to me (roberto tyley at gmail), so I can check I'm fixing your issue.
