### ISSUE TITLE
Checkout repository to non default location

### ISSUE THREAD

**Issue by berndhirschler** [rtyley/agit#36]
When you checkout a repository to a non default location, the repository is not shown in the overview of available repositories in agit.

**Comment by rtyley** [comment]
Yes, this is true... at the moment Agit just scans the 'git-repos' directory on your sdcard, and lists the repos it finds there. The right thing to do would be to ensure all repo locations are in a db, so they can be found even if they're not in the 'git-repos' directory. This has been fairly low priority for me so far - I've been concentrating on other features!

I've been using the 'non default location' function to let me check out a repo more than once (for testing purposes) or to checkout two different repos with similar names (ie I change the leaf folder name but don't remove it from the 'git-repos' folder).

I'm just curious, to help me prioritise this, is there a use-case for cloning a repo to a location outside of the default directory?

**Comment by berndhirschler** [comment]
Yes, of course there is a use case! :-D

I have my personal stuff in a repository, ringtones/notification/wallpaper
and the best stuff all my notes from tomboy (I use tomdroid on android).
On my Desktop/Notebook runs sparkleshare, so all the information is always
synchronized to my server. My mobile has now the same awesome feature,
thanks to you.

The problem only came up, because the folders for all that stuff have a
fixed location on the sdcard, otherwise the android os does not find them.

Maybe I find some time on the weekend and take a look at the source. If
something nice comes out I will let you know. Can you maybe point me into
the right direction, than my help could be more effective.

## 

Kind regard
Bernd
:x

**Comment by dodgyville** [comment]
I have a game written using the pgs4a framework (python + pygame). During testing pgs4a requires your game files to be inside /sdcard/pygame/   ... so for my dev work I'd ideally have my checkout inside /sdcard/pygame ... I guess I can do it using a symlink but I'd rather have agit remember the custom directories. Agit is a nifty app - has some great potential.

**Comment by andrewcstewart** [comment]
Absolutely.  I'd like to use Agit to manage /mnt/sdcard/sl4a/scripts for Android scripting engine.

Wouldn't a really simple solution be to just create a symlink to the non-default location within the git-repos directory?

**Comment by dodgyville** [comment]
Unfortunately the majority of sd cards on android devices are formatted fat32, which means symlinks won't work. You can reformat your card to something else like ext3 but that is treating the symptom not the problem.

**Comment by andrewcstewart** [comment]
@rtyley , would it be difficult to simply keep the list of repositories in a text file, allowing the existence of repos outside of git-repos?  

repos1 path1
repos2 path2

etc.  Would you welcome help with this?  It's valuable enough to me to spend my time on if you're interested.
