### ISSUE TITLE
Updating doesn't update working copy

### ISSUE THREAD

**Issue by aragaer** [rtyley/agit#37]
I created a non-bare repository (for which I has to untick the 'bare' flag; why would I want a bare repository at all?). Then remote was updated and I tried to update my local repository. While I can see logs and later commits, the code in local repo is still old.

**Comment by rtyley** [comment]
Gah, you're right. Obviously, if it's a non-bare repo, you'd want the repo to checkout the latest HEAD on your current branch. At the moment a refresh is only doing a 'fetch' -so you can see updated logs, but the state of the working directory doesn't change.

When using Agit just to follow the progress of an open source software project, you probably only want to see the latest commits, and maybe their diffs- not actually update the working directory (a disproportionally slow step on the sdcard) for, eg, a compile... the checkout step is slow enough that I made 'bare' the default for clone operations.

I'll get on fixing this now...

**Comment by aragaer** [comment]
Great. What about submodules? Our should I create a separate issue for that?

**Comment by rtyley** [comment]
Unfortunately submodules aren't supported by JGit (the underlying Java Git library used by Agit):

https://bugs.eclipse.org/bugs/show_bug.cgi?id=314853

Various people have been asking for submodule support in JGit for a while, but I don't think anyone's actually got round to doing it...

**Comment by boryn** [comment]
I'd suggest switching names for the "Bare" option - I'd rather name it "Create working directory" and by default made it unchecked. As for me - "Create working directory" is by far more clear what it would do after the cloning than just bare "Bare" option :)

**Comment by aragaer** [comment]
"Bare" is the standard name used in git. As in a "git clone --bare"

**Comment by boryn** [comment]
Yes, yes, I know what "Bare repository" is - I just share the experience of the first time user and think that reversing the names would just be more clear.

**Comment by rtyley** [comment]
1177e46 closed this issue - pushed out with 1.25
