### ISSUE TITLE
Illegible user info window

### ISSUE THREAD

**Issue by boryn** [rtyley/agit#41]
I tapped on the author and got this screen: http://screencast.com/t/JG3R5Vi9. Unfortunately you cannot read there anything :) At least on Samsung Galaxy S2 where I tested. 

PS. How to update the gravatar of the user?

**Comment by rtyley** [comment]
b7a51fc looks to fix the styling - screenshots here from Froyo and ICS:

https://picasaweb.google.com/100348950724173674512/AgitIssue41IllegiblePersonDialog

Thank Adam Powell for his informative post on contexts and theming :)

https://plus.google.com/107708120842840792570/posts/VTeRBsAeyTi

**Comment by rtyley** [comment]
this has been released to the Android Market with Agit v1.28.
