### ISSUE TITLE
Reading the code

### ISSUE THREAD

**Issue by miniBill** [rtyley/agit#43]
Do you have any links on resources to read before being able to comprehend you code?
Specifically, all the @Inject stuff is completely throwing me off

**Comment by rtyley** [comment]
Hi @miniBill - I've just created this page, it's small at the moment but it does at least link to the Guice guide for the @Inject annotation:

https://github.com/rtyley/agit/wiki/Understanding-the-code-of-Agit

**Comment by miniBill** [comment]
Will read :-)
