### ISSUE TITLE
NPE on checkout of non-bare Clone for some repos

### ISSUE THREAD

**Issue by rtyley** [rtyley/agit#47]
Doesn't affect all repos, thankfully... but doing a non-bare clone on this (very simple) repo dies:

https://github.com/rtyley/five-mb-file-test-repo

-non-bare clone does work for some repos, so why does it fail for this?

The NPE in Inflater.java:295 is apparently caused by 'streamHandle' equaling -1...

```
public synchronized void reset() {
    if (streamHandle == -1) {
        throw new NullPointerException();
    }
    finished = false;
    needsDictionary = false;
    inLength = inRead = 0;
    resetImpl(streamHandle);
}
```

On a regular computer, this works:

java -cp ~/development/jgit/org.eclipse.jgit.pgm/target/jgit-cli.jar  org.eclipse.jgit.pgm.Main clone https://github.com/rtyley/five-mb-file-test-repo.git
Initialized empty Git repository in /home/roberto/development/agit-debugging/five-mb-file-test-repo/.git
remote: Counting objects: 3
remote: Compressing objects: 100% (2/2)
Receiving objects:      100% (3/3)
Updating references:    100% (1/1)
remote: Total 3 (delta 0), reused 3 (delta 0)
From https://github.com/rtyley/five-mb-file-test-repo.git
- [new branch]      master     -> origin/master

E/GAT     (  811): Examining exception java.lang.NullPointerException op Clone[https://github.com/rtyley/five-mb-file-test-repo.git] cancelled=false
E/GAT     (  811): java.lang.NullPointerException
E/GAT     (  811):  at java.util.zip.Inflater.reset(Inflater.java:295)
E/GAT     (  811):  at org.eclipse.jgit.lib.HarmonyFixInflater.reset(HarmonyFixInflater.java:88)
E/GAT     (  811):  at org.eclipse.jgit.lib.InflaterCache.release(InflaterCache.java:92)
E/GAT     (  811):  at org.eclipse.jgit.storage.file.WindowCursor.release(WindowCursor.java:347)
E/GAT     (  811):  at org.eclipse.jgit.storage.file.PackInputStream.close(PackInputStream.java:83)
E/GAT     (  811):  at java.io.FilterInputStream.close(FilterInputStream.java:65)
E/GAT     (  811):  at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:280)
E/GAT     (  811):  at java.io.BufferedInputStream.close(BufferedInputStream.java:132)
E/GAT     (  811):  at org.eclipse.jgit.lib.ObjectStream$Filter.close(ObjectStream.java:229)
E/GAT     (  811):  at org.eclipse.jgit.lib.ObjectLoader.copyTo(ObjectLoader.java:263)
E/GAT     (  811):  at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:915)
E/GAT     (  811):  at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:441)
E/GAT     (  811):  at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:380)
E/GAT     (  811):  at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:227)
E/GAT     (  811):  at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
E/GAT     (  811):  at com.madgag.agit.operations.Clone.execute(Clone.java:57)

**Comment by rtyley** [comment]
The cause is a difference in the `InflaterInputStream.close()` method in Oracle Java vs the Android (Harmony?) implementation:

**Oracle** (Java 6):

``` java
public void close() throws IOException {
    if (!closed) {
        if (usesDefaultInflater)
            inf.end();
        in.close();
        closed = true;
    }
}
```

**Android** (identical to [Harmony implementation](http://svn.apache.org/viewvc/harmony/enhanced/java/trunk/classlib/modules/archive/src/main/java/java/util/zip/InflaterInputStream.java?revision=929253&view=markup&pathrev=1003513)):

``` java
public void close() throws IOException {
    if (!closed) {
        inf.end();
        closed = true;
        eof = true;
        super.close();
    }
}
```

JGit has an InflaterCache which it uses to recycle Inflaters - and it also uses InflaterInputStream to uncompress blobs. The Oracle implementation of `InflaterInputStream.close()` won't `end()` your Inflater if you supplied it (ie if it came from your cache of Inflaters), but the Android implementation will - it doesn't have a `usesDefaultInflater` variable to track if the inflater was externally supplied or not :-(

In the case of Android, you get this train-wreck happening:

```
01-14 21:37:51.413 W/System.err(  501):     at com.madgag.android.jgit.HarmonyFixInflater.reset(HarmonyFixInflater.java:125)
01-14 21:37:51.413 W/System.err(  501):     at org.eclipse.jgit.lib.InflaterCache.release(InflaterCache.java:95)
01-14 21:37:51.413 W/System.err(  501):     at org.eclipse.jgit.storage.file.WindowCursor.release(WindowCursor.java:347)
01-14 21:37:51.413 W/System.err(  501):     at org.eclipse.jgit.storage.file.PackInputStream.close(PackInputStream.java:83)
01-14 21:37:51.413 W/System.err(  501):     at java.io.FilterInputStream.close(FilterInputStream.java:65)
01-14 21:37:51.413 W/System.err(  501):     at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:280)
```

...the `InflaterInputStream.close()` implementation directly calls the `end()` method, then `super.close()` gets called, which closes it's source, a JGit `PackInputStream` which releases it's `WindowCursor`, which in turn attempts to return it's `Inflater` to the pool - but that calls `reset()` - and **you can't perform any op** on an `Inflater` after it's been ended.

**Comment by rtyley** [comment]
A patch to fix Android's implementation of `InflaterInputStream` has been submitted for review here:

https://android-review.googlesource.com/#/c/31580/

**Comment by bnjmnt4n** [comment]
Is it possible to include this fix in JGit itself?
