### ISSUE TITLE
Build fails with "Unable to find the mojo 'generate-sources'"

### ISSUE THREAD

**Issue by aaronp24** [rtyley/agit#48]
Fresh clone at commit 261b1a6b3321529797cd356abd31d40f3a78ea7c with a fresh install of Maven, following the instructions at https://github.com/rtyley/agit/wiki/Building-Agit

~/git/agit/agit$ mvn compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Agit - git client for Android
[INFO]    task-segment: [compile]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to assets/
[INFO] Copying 1 resource to /home/aaron/git/agit/agit/target/filtered-manifest
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'com.jayway.maven.plugins.android.generation2:maven-android-plugin:3.0.0-alpha-6:generate-sources': Unable to find the mojo 'generate-sources' (or one of its required components) in the plugin 'com.jayway.maven.plugins.android.generation2:maven-android-plugin'
Component descriptor cannot be found in the component repository: org.sonatype.aether.RepositorySystem.
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Wed Sep 14 10:57:24 PDT 2011
[INFO] Final Memory: 23M/238M
[INFO] ------------------------------------------------------------------------

**Comment by aaronp24** [comment]
git bisect says this was broken by commit 95b1ff877edf69a9a65c97e400c5b1b57d776d5e

**Comment by rtyley** [comment]
I can reproduce this issue using Maven 2.2.1 :

$ mvn -v
Apache Maven 2.2.1 (rdebian-1)
Java version: 1.6.0_26
Java home: /usr/lib/jvm/java-6-sun-1.6.0.26/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux" version: "2.6.32-33-generic" arch: "i386" Family: "unix"

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'com.jayway.maven.plugins.android.generation2:maven-android-plugin:3.0.0-alpha-6:generate-sources': Unable to find the mojo 'generate-sources' (or one of its required components) in the plugin 'com.jayway.maven.plugins.android.generation2:maven-android-plugin'
Component descriptor cannot be found in the component repository: org.sonatype.aether.RepositorySystem.
[INFO] ------------------------------------------------------------------------

**Comment by rtyley** [comment]
Although I can reproduce it using Maven 2.2.1, the build works successfully with Maven 3.0.3 (which is what I normally use). Agit has been using the latest 3.0.0 stream of the [Maven Android Plugin](http://code.google.com/p/maven-android-plugin/wiki/Changelog) for some time now, and MAP 3 requires Maven v3.0.3... I've updated this page to reflect the requirement:

https://github.com/rtyley/agit/wiki/Building-Agit

Could you check that upgrading to Maven 3.0.3 resolves your problem?

Nice use of git bisect by the way :)

**Comment by aaronp24** [comment]
Sorry I haven't gotten around to trying this yet.  Neither Ubuntu nor Debian seems to have a package for Maven 3, so I'll have to install it manually and I haven't had a chance to give that a try.

**Comment by rtyley** [comment]
Installing Maven 3 on Ubuntu isn't so bad - though admittedly I do it differently every time I do a fresh install!

This blog post is fairly concise:

http://blog.btmatthews.com/2011/08/04/installing-maven-3-on-ubuntu-11-04-lts-server/

I think you might need to set M2_HOME as well, I'm not sure...

**Comment by manandbytes** [comment]
Unfortunately, prerequisites in MAP's POM doesn't work, as it should fail build because of using M2 but it doesn't.
