### ISSUE TITLE
about building agit in intellij idea

### ISSUE THREAD

**Issue by vikassable** [rtyley/agit#60]
hello sir,
My self vikas sable. I want to build agit . I have tried it on eclipse but i get lots of problems so i switched to intellij idea. Here also
i am getting  lots of problem . Please i request you to send the procedure of building agit in intellij idea.
                                                                                                                                                                                   with regards.
                                                                                                                                                                            vilkas sable

**Comment by rtyley** [comment]
Hi @vikassable - I'm afraid your question is too vague to be answered at this point, as you don't specify exactly what your problems are with using Intellij. Please check that you've followed the steps at:

https://github.com/rtyley/agit/wiki/Building-Agit

I just rechecked using Intellij 11 and was able to import the project just fine. In general, to build the project itself, I will use the maven command:

```
mvn clean install
```
