### ISSUE TITLE
Please help! Clone test on android

### ISSUE THREAD

**Issue by dirong** [rtyley/agit#63]
I created test android app.  In app i call clone operation used jgit and i get error : 
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:125)
org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:228)
org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:926)
org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:444)
org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:378)
org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:224)
org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
But in agit, this operation is executed without error. I studied your code, but did not understand why this is happening.
Tell me, what i doing wrong?
My code:
public void clone(File dir, String uri){
                        Git.cloneRepository()
            .setBare(false)
            .setDirectory(dir)
            .setCloneAllBranches(false)
            .setRemote("origin")
            .setURI(uri)
            .call();
}

**Comment by rtyley** [comment]
Hi @dirong - that's an interesting error, but as it's a problem with your code, and not Agit, it's not appropriate to open an issue against this repo.

If you ask a question on http://stackoverflow.com/ then it can be much more usefully found and discussed - I'll be happy to contribute what I know there.
