### ISSUE TITLE
About my issue

### ISSUE THREAD

**Issue by vikassable** [rtyley/agit#64]
thank you sir for addressing my issue. But i have already solved the problem. I am working on your project . I want to provide basic git functionality on android device. I have integrated git status, add, commit with your application. Currently i am working on git push. Sir , if you have any suggestion i am very lucky to listen you. Very Very Thanks........................ again.

**Comment by rtyley** [comment]
@vikassable sounds like you're making progress! I just want to remind you that Agit is released under the GPL v3 license - so if you distribute your work you will also need to distribute the source under the GPL v3 license.

http://www.gnu.org/copyleft/gpl.html

Incidentally, GitHub issues are only intended to be used with bug/feature-requests, so please don't open new issues as a form of general communication :)
