### ISSUE TITLE
Diff bar display error

### ISSUE THREAD

**Issue by agryson** [rtyley/agit#65]
When opening up a file in diff view, the diff slider appears at 100% (only show the current state) but the file is displayed as if it were at 50% (you see both old and new code). 

I think this is because of line 65 in _agit/src/main/java/com/madgag/agit/diff/DiffSliderView.java_ where you have:

``` java
seekBar.setProgress(seekBar.getMax());
```

Unless I'm mistaken (and I may be), it should read:

``` java
seekBar.setProgress(seekBar.getMax()/2);
```

so that the seekbar is at 50% when it's initialized to correctly reflect what's visible in the preview.

If you're very busy I'll try it out myself and submit a pull request once it's squashed, just thought to put the issue here just in case.

**Comment by rtyley** [comment]
Hi @agryson thanks for the great issue report, much appreciated. I see you have a branch up now with this change, would you like to submit it as a pull request?

**Comment by agryson** [comment]
I wanted to build and test before submitting a pull request (though eclipse is making me tear my hair out right now trying to install m2e!).
If you're confident that this is a valid fix for the problem (you know your code better than I do!) I can skip the formality and issue a pull request for testing on your end. Might be another day or two before I get it built otherwise.

**Comment by rtyley** [comment]
sorry to hear about the problems building Agit, you've probably already seen this, I guess?

https://github.com/rtyley/agit/wiki/Building-Agit

I tried both Eclipse and Intellij while developing Agit, and ended up settling on IntelliJ, which just seemed to handle the combination rather better out of the box:

http://stackoverflow.com/a/9491525/438886

If you just want to test your code fixes the problem, you can also just compile from the command line with `mvn clean install` - some of the integration tests may fail unless you have a properly configured Android device attached, but the required APK will still have been installed and you'll be able to check it works as expected.

**Comment by agryson** [comment]
No worries, and it's not agit, just eclipse being eclipse with weird plugin installation behaviour- the instructions on the wiki are clear. As I had eclipse I started with it... my first mistake.
I'll build from command line first chance I get and come back to you.

**Comment by agryson** [comment]
Built and tested successfully, pull request submitted.
