### ISSUE TITLE
app not available in your country

### ISSUE THREAD

**Issue by shvelo** [rtyley/agit#74]
unable to install from gplay
wtf

**Comment by rtyley** [comment]
Hi @shvelo - you didn't specify what country you're using Google Play in, but I'm guessing from your profile that it's Georgia?

I've enabled Agit for all countries listed in the Google Play admin console, unfortunately I don't see Georgia in the list. You might want to try the alternative Europe-friendly AndroidPit market listing:

http://www.androidpit.com/en/android/market/apps/app/com.madgag.agit/Agit-Git-client

Let me know if that helps!

best regards,
Roberto

**Comment by shvelo** [comment]
I think you should uncheck all of them.
And yes it's Georgia.
Oh sorry it's because the app is paid

**Comment by rtyley** [comment]
Yep, looks like paid apps are only available in certain countries (currently doesn't include Georgia):

http://support.google.com/googleplay/bin/answer.py?hl=en&answer=143779

You can try the alternative AndroidPit market, which I think may be available in your country:

http://www.androidpit.com/en/android/market/apps/app/com.madgag.agit/Agit-Git-client

Alternatively, as Agit is open-source, you're free to build it yourself from the original source code - see

https://github.com/rtyley/agit/wiki/Building-Agit

**Comment by shvelo** [comment]
Why is it paid if it's opensource?
