### ISSUE TITLE
Gerrit server is required for tests

### ISSUE THREAD

**Issue by Vanuan** [rtyley/agit#83]
As far as I understood, the server is required for tests.
Is it really needed?
Can't local server be used?

**Comment by rtyley** [comment]
The integration tests are there to ensure that several aspects of Git cloning (including SSH functionality) are operational. Setting up fake user accounts for the Agit instance to SSH into on new CI environments/dev machines (eg my laptop, frequently _without_ internet access) is a sufficiently large hassle that including a mini-git-server (stripped-down Gerrit) in the integration-tests themselves was preferable to me :)

**Comment by Vanuan** [comment]
So, don't the integration tests start up a git server and setup SSH? Do I need to do that manually?

**Comment by rtyley** [comment]
The integration tests start & stop the mini-git-server (which has in-built ssh support on a non-default port) using the `cargo-maven2-plugin` - see here:

https://github.com/rtyley/agit/blob/971e2ec7d/agit-integration-tests/pom.xml#L156-L197

This should happen automatically for you if you run `mvn clean install`

**Comment by Vanuan** [comment]
Thanks! I've figured out that already. And I've configured Travis CI. Could you please review my pull requests?
